# Generated by Django 3.2.13 on 2023-05-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faqitem_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
