# Generated by Django 3.2.20 on 2024-01-23 14:50

from django.db import migrations

def update_is_deleted_true(apps,schema_editor):
    FAQItems = apps.get_model('faq','FAQItem')
    FAQItems.objects.filter(is_deleted=False, deleted_at__isnull=False).update(is_deleted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_faqitem_is_deleted'),
    ]

    operations = [
        migrations.RunPython(update_is_deleted_true),
    ]
