stages:
  # - test
  # - lint
  #- test # pour SAST sinon plante
  - quality
  - build
  - deploy

include:
  #- template: Security/SAST.gitlab-ci.yml
  - local: "/workflows/.gitlab-ci-integration.yml"
  - local: "/workflows/.gitlab-ci-build.yml"
  - local: "/workflows/.gitlab-ci-deploy.yml"
