stages:
  - securitycheck
  - test
  - security
  - quality
  - build
  - deploy

include:
  - local: "/workflows/.gitlab-ci-securitycheck.yml"
  - local: "/workflows/.gitlab-ci-integration.yml"
  - local: "/workflows/.gitlab-ci-build.yml"
  - local: "/workflows/.gitlab-ci-deploy.yml"
