version: '3'

volumes:
  dbdata:

services:
  rabbitmq:
    restart: always
    image: ${DOCKER_REGISTRY}rabbitmq:3.8.2-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=ecc
      - RABBITMQ_DEFAULT_PASS=ecc
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'

  postgres:
    image: ${DOCKER_REGISTRY}postgres:11
    environment:
      - POSTGRES_USER=ecc
      - POSTGRES_PASSWORD=ecc
      - POSTGRES_DB=ecc
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./backup:/backup

  django:
    image: econtrole
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
        PROXY_CC_URL: ${PROXY_CC_URL}
        REGISTRY_DOMAINE: ${REGISTRY_DOMAINE}
    volumes:
      - '.:/code'
    ports:
      - '8080:8080'
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - PORT=8080
    command: "./startLocal.sh"
