# Generated by Django 3.2.13 on 2023-05-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0007_alter_parametre_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametre',
            name='is_deleted',
        ),
    ]
