# Generated by Django 3.2.13 on 2023-05-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_remove_parametre_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
