.deploy:
  image: ${DOCKER_REGISTRY}cicd/cicd-tool:5.2.1
  stage: deploy
  variables: &deploy_variables
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_REGISTRY_IMAGE: ${DOCKER_REGISTRY}${DOCKER_REGISTRY_NAMESPACE}${IMAGE_NAME}:${IMAGE_TAG}
  script:
    - set -o allexport
    - source ${CONFIG_FILE}
    - set +o allexport
    - >
      cd-tools --host ${SSH_HOST} --user ${SSH_USER} --password ${SSH_PASSWORD}
      ssh-command "docker rm -f ${CONTAINER_NAME} || true"
    - |
      export COMMAND
      COMMAND="docker run --name ${CONTAINER_NAME} --network=\"host\" --user ${USER_ID}:${GROUP_ID} --restart always -d"
      COMMAND="$COMMAND -v ${MEDIA_PATH}:/code/e-controle-media"
      COMMAND="$COMMAND -v ${STATIC_PATH}:/var/ecc/static"
      COMMAND="$COMMAND -v ${LOG_PATH}:/var/log"
      COMMAND="$COMMAND -e DEBUG=${DEBUG}"
      COMMAND="$COMMAND -e SHOW_DEBUG_TOOLBAR=False"
      COMMAND="$COMMAND -e DATABASE_URL=\"${DATABASE_URL}\""
      COMMAND="$COMMAND -e SECRET_KEY=\"${SECRET_KEY}\""
      COMMAND="$COMMAND -e CELERY_BROKER_URL=${CELERY_BROKER_URL}"
      COMMAND="$COMMAND -e MEDIA_ROOT=/code/e-controle-media"
      COMMAND="$COMMAND -e STATIC_ROOT=/var/ecc/static"
      COMMAND="$COMMAND -e EMAIL_HOST=${EMAIL_HOST}"
      COMMAND="$COMMAND -e EMAIL_PORT=${EMAIL_PORT}"
      COMMAND="$COMMAND -e EMAIL_HOST_USER=${EMAIL_HOST_USER}"
      COMMAND="$COMMAND -e EMAIL_HOST_PASSWORD=\"${EMAIL_HOST_PASSWORD}\""
      COMMAND="$COMMAND -e EMAIL_TIMEOUT=${EMAIL_TIMEOUT}"
      COMMAND="$COMMAND -e EMAIL_USE_TLS=True"
      COMMAND="$COMMAND -e DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}"
      COMMAND="$COMMAND -e SUPPORT_TEAM_EMAIL=${SUPPORT_TEAM_EMAIL}"
      COMMAND="$COMMAND -e SEND_EMAIL_WHEN_USER_ADDED=${SEND_EMAIL_WHEN_USER_ADDED}"
      COMMAND="$COMMAND -e SEND_EMAIL_WHEN_USER_REMOVED=${SEND_EMAIL_WHEN_USER_REMOVED}"
      COMMAND="$COMMAND -e MAGICAUTH_TOKEN_DURATION_SECONDS=${MAGICAUTH_TOKEN_DURATION_SECONDS}"
      COMMAND="$COMMAND -e LDAP_SERVER=${LDAP_SERVER}"
      COMMAND="$COMMAND -e LDAP_DOMAIN=${LDAP_DOMAIN}"
      COMMAND="$COMMAND -e HTTP_AUTHORIZATION=\"${HTTP_AUTHORIZATION}\""
      COMMAND="$COMMAND -e LDAP_USER=${LDAP_USER}"
      COMMAND="$COMMAND -e LDAP_PASSWORD=\"${LDAP_PASSWORD}\""
      COMMAND="$COMMAND -e LDAP_DC=${LDAP_DC}"
      COMMAND="$COMMAND -e AUTH_LDAP_REQUIRE_GROUP=${AUTH_LDAP_REQUIRE_GROUP}"
      COMMAND="$COMMAND -e WEBDAV_URL=${WEBDAV_URL}"
      COMMAND="$COMMAND -e ADMIN_URL=\"${ADMIN_URL}\""
      COMMAND="$COMMAND -e QUESTIONNAIRE_SITE_URL=\"${QUESTIONNAIRE_SITE_URL}\""
      COMMAND="$COMMAND -e SESSION_EXPIRE_SECONDS=86400"
      COMMAND="$COMMAND -e UPLOAD_FILE_EXTENSION_BLACKLIST=\"${UPLOAD_FILE_EXTENSION_BLACKLIST}\""
      COMMAND="$COMMAND -e DEMO_INSPECTOR_USERNAME=${DEMO_INSPECTOR_USERNAME}"
      COMMAND="$COMMAND -e DEMO_AUDITED_USERNAME=${DEMO_AUDITED_USERNAME}"
      COMMAND="$COMMAND -e ALLOW_DEMO_LOGIN=${ALLOW_DEMO_LOGIN}"
      COMMAND="$COMMAND -e PORT=${SERVER_PORT}"
      COMMAND="$COMMAND -e HOSTNAME=${SSH_HOST}"
      COMMAND="$COMMAND -e PIWIK_TRACKER_BASE_URL=\"${PIWIK_TRACKER_BASE_URL}\""
      COMMAND="$COMMAND -e PIWIK_SITE_ID=${PIWIK_SITE_ID}"
      COMMAND="$COMMAND ${DOCKER_REGISTRY_IMAGE}"
    - >
      cd-tools --host ${SSH_HOST} --user ${SSH_USER} --password ${SSH_PASSWORD}
      ssh-command "${COMMAND}"

.deploy_rabbitmq:
  image: ${DOCKER_REGISTRY}cicd/cicd-tool:5.2.1
  stage: deploy
  variables: &deploy_rabbitmq_variables
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: "rabbitmq"
  script:
    - >
      cd-tools --host ${SSH_HOST} --user ${SSH_USER} --password ${SSH_PASSWORD}
      ssh-command "docker rm -f ${CONTAINER_NAME} || true"
    - |
      export COMMAND
      COMMAND="docker run --name ${CONTAINER_NAME} -p ${RABBITMQ_UI_PORT}:15672 -p ${RABBITMQ_PORT}:5672 --restart always -d"
      COMMAND="$COMMAND -e RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
      COMMAND="$COMMAND -e RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
      COMMAND="$COMMAND ${DOCKER_REGISTRY_RABBITMQ}${IMAGE_NAME}:${IMAGE_TAG}"
    - >
      cd-tools --host ${SSH_HOST} --user ${SSH_USER} --password ${SSH_PASSWORD}
      ssh-command "${COMMAND}"

# Deploy to dev2 env
deploy:commit:dev2_e-controle:
  extends:
    - .deploy
  when: manual
  variables:
    <<: *deploy_variables
    IMAGE_TAG: $CI_COMMIT_SHA
    IMAGE_NAME: e-controle
    CONTAINER_NAME: e-controle
    SERVER_PORT: 8080
    MEDIA_PATH: /opt/e-controle-media
    STATIC_PATH: /opt/e-controle-static
    LOG_PATH: /opt/e-controle-log
  needs:
    - build:commit
  environment:
    name: Dev2

deploy:commit:dev2_e-controle-webdav:
  extends:
    - .deploy
  when: manual
  variables:
    <<: *deploy_variables
    IMAGE_TAG: $CI_COMMIT_SHA
    IMAGE_NAME: e-controle-webdav
    SERVER_PORT: 8081
    MEDIA_PATH: /opt/e-controle-media
    STATIC_PATH: /opt/e-controle-static
    LOG_PATH: /opt/e-controle-log
  needs:
    - build:commit_webdav
  environment:
    name: Dev2

deploy:commit:rabbitmq:
  extends:
    - .deploy_rabbitmq
  when: manual
  variables:
    <<: *deploy_rabbitmq_variables
    IMAGE_TAG: 3.8.2-management
    IMAGE_NAME: rabbitmq
    CONTAINER_NAME: rabbitmq
    RABBITMQ_UI_PORT: 15672
    RABBITMQ_PORT: 5672
  environment:
    name: Dev2


# Deploy to RepriseCollectePro env
deploy:commit:reprise_collecte_pro_e-controle:
  extends:
    - .deploy
  when: manual
  variables:
    <<: *deploy_variables
    IMAGE_TAG: $CI_COMMIT_SHA
    IMAGE_NAME: e-controle
    CONTAINER_NAME: e-controle-collecte-pro
    SERVER_PORT: 8082
    MEDIA_PATH: /opt/e-controle-collecte-pro-media
    STATIC_PATH: /opt/e-controle-collecte-pro-static
    LOG_PATH: /opt/e-controle-collecte-pro-log
  needs:
    - build:commit
  environment:
    name: RepriseCollectePro

deploy:commit:rabbitmq_reprise_collecte_pro:
  extends:
    - .deploy_rabbitmq
  when: manual
  variables:
    <<: *deploy_rabbitmq_variables
    IMAGE_TAG: 3.12.4
    IMAGE_NAME: rabbitmq
    CONTAINER_NAME: rabbitmq-collecte-pro
    RABBITMQ_UI_PORT: 15673
    RABBITMQ_PORT: 5673
  environment:
    name: RepriseCollectePro
