# Generated by Django 3.2.13 on 2023-05-30 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0046_auto_20230530_1028'),
        ('user_profiles', '0016_auto_20210802_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil Utilisateur', 'verbose_name_plural': 'Profils Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='controls',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('audited', 'Organisme interrogé'), ('inspector', 'Demandeur')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='send_files_report',
            field=models.BooleanField(default=True, help_text='Envoyer par email le rapport des fichiers déposés ?', verbose_name='Envoi Rapport de Fichiers'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('repondant', 'Répondant'), ('demandeur', 'Demandeur')], max_length=255)),
                ('control', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='access', to='control.control')),
                ('userprofile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='user_profiles.userprofile', verbose_name='userprofile')),
            ],
            options={
                'verbose_name': "Accès d'un utilisateur à un contrôle",
                'verbose_name_plural': 'Accès des utilisateurs à des contrôles',
            },
        ),
    ]
