# Generated by Django 3.2.13 on 2023-05-16 08:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CGUItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Item de C.G.U.',
                'verbose_name_plural': 'Items de C.G.U.',
                'ordering': ('order',),
            },
        ),
    ]
