# Generated by Django 3.2.13 on 2023-05-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cguitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
