# Generated by Django 3.2.13 on 2023-04-25 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0044_auto_20230404_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='reference_code',
            field=models.CharField(error_messages={'unique': 'UNIQUE'}, help_text='Ce code est utilisé notamment pour le dossier de stockage des réponses', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='INVALID', regex='^[\\s\\w-]+[^\\.]$')], verbose_name='code de référence'),
        ),
    ]
