# Generated by Django 3.2.18 on 2023-11-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0045_alter_control_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
