# Generated by Django 3.2.18 on 2023-11-11 19:47

import control.models
import control.upload_path
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0046_control_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date de transmission du questionnaire', null=True, verbose_name="date d'envoi"),
        ),
        migrations.AlterField(
            model_name='responsefile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Ce fichier est-il dans la corbeille ?', verbose_name='Supprimé'),
        ),
        migrations.CreateModel(
            name='QuestionnaireFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('file', models.FileField(upload_to=control.upload_path.questionnaire_pj_file_path, verbose_name='fichier')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_files', to='control.questionnaire', verbose_name='questionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire: Fichier Annexe',
                'verbose_name_plural': 'Questionnaire: Fichiers Annexes',
                'ordering': ('questionnaire', 'order'),
            },
            bases=(models.Model, control.models.FileInfoMixin),
        ),
    ]
