# Generated by Django 3.2.13 on 2023-10-12 13:31

import control.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0046_auto_20230530_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsefile',
            name='file',
            field=models.FileField(upload_to=control.upload_path.response_file_path, verbose_name='fichier'),
        ),
    ]
