# Generated by Django 3.2.20 on 2023-11-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0047_alter_responsefile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'Contrôle', 'verbose_name_plural': 'Contrôles'},
        ),
    ]
