# Generated by Django 3.2.20 on 2024-01-22 17:05

from django.db import migrations

def update_is_deleted_true(apps, schema_editor):
    Control = apps.get_model('control', 'Control')
    Control.objects.filter(is_deleted=False, deleted_at__isnull=False).update(is_deleted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0048_alter_control_options'),
    ]

    operations = [
        migrations.RunPython(update_is_deleted_true),
    ]
